language: node_js
node_js:
- '5'
branches:
  only:
  - master
before_install:
- npm install -g hexo
- npm install
- cd themes/tranquilpeak/
- npm install
- bower install
- npm run prod
- cd ../../
install:
- hexo generate
- hexo aloglia
before_script:
- git config --global user.name 'Graham Cox via Travis CI'
- git config --global user.email 'graham@grahamcox.co.uk'
- sed -i'' "s~git@github.com:openassistive/OATSoft.git~https://${GH_TOKEN}:x-oauth-basic@github.com/openassistive/OATSoft.git~"
  _config.yml
script:
- hexo deploy --silent
env:
  global:
    secure: nkpYRBFa/fY6J2jZvzPRjI8Up/9beKZX+bbUt+A9OA48lUOrNbE5rTUVe3HDVMxSdYuN1QvUJcrH12d2dasG4Bq146HEXsB7wroO8rViZvROqOsy47uubLZ1e+2mCDi+hHF62CAcz6l8KkihbdO4qH3o2WbPXAuIL1BBi1Kl81XzYsMn1136sKsGgWFlX+kxhuErsKT/sY4eEGGIETtb0Ctrfo5TO7XHQJ85E//WsO6DAViDbtBW4Dw8AjrYXBKtEMU/1DW7FgbHTPXJ2yJt6ezgjI4eWSE3nRhOTrSSn+iHSwwfk9WrLEhDEcqfxCBzIwlSx38zYNz7eC4/fL6MofemO3ZbJuqwFwZJGgxJ/Nm0ZctcDwxoU81zzOMjlsulEmXIcps42+IQWon41KWcnxTWf2nPpZChJ3UIbx3wgCJ4s9T5GgdHNTjtS7dkUOKESyBj0Oqsf2BpZmaEwCrY6BSG+B+WeIYwHlEeMWdy8nD2MslJlSTx6E237WBuRZvl6bBiYcgGr1QsBDUTa36MYWmZgUfZO8271Rubv9DfmRfPwj1V6wvkhsDtFTYFXZvOzY0XmVtwZN6pIXYnav9qNu80MNGQnuJFvmmPM/3gWdIhKfcUQSrGSAYyZVcYujDp8O9KCtv8ddkU4rF3seEKRBnsGdeH/PcDHU+S8OJ4aU8=
